helm:
  parameters:
  - name: replicaCount
    value: "3"
    forcestring: false
  - name: image.repository
    value: ademxzaghouane/express-sqlite-app
    forcestring: false
  - name: image.tag
    value: v0.5
    forcestring: true
  - name: image.name
    value: ademxzaghouane/express-sqlite-app
    forcestring: true
