helm:
  parameters:
  - name: image.repository
    value: ademxzaghouane/express-sqlite-app
    forcestring: false
  - name: image.tag
    value: v0.7
    forcestring: true
  - name: image.name
    value: ademxzaghouane/express-sqlite-app
    forcestring: true
